apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
    target:
      kind: Deployment
      name: backend

configMapGenerator:
  - name: app-config
    literals:
      - ENVIRONMENT=production

resources:
  - monitoring.yaml
  - autoscaling.yaml