name: Frontend CI

on:
  push:
    paths:
      - 'client/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - name: Install dependencies
      run: |
        cd client
        npm ci

    - name: Run tests
      run: |
        cd client
        npm test -- --coverage

    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        directory: ./client/coverage